### ISSUE TITLE
Can't emulate iOS at times

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#22]
I'm not sure I'll be able to replicate this, but after playing for about 20 minutes, and working on a new app, I can't emulate to iOS. It is stuck on "Your application is launching for iOS".

Logs don't show anything interesting: (ugh, can't copy Logs, will file a new bug for that)
Console shows an issue w/ livereload, but I had the server up in another app so I don't think it is related.

Will post more details if I can.

**Comment by cfjedimaster** [comment]
Restarted Lab, still can't emulate this new app. Still nothing interesting in the logs.

**Comment by cfjedimaster** [comment]
This seems to be _just_ with new projects. When I open an existing project, it can emulate iOS ok.

The last item in the log for 2 new apps that won't emulate is:
Wrote out iOS Bundle Version to "0.0.1"

**Comment by cfjedimaster** [comment]
Building for iOS also seems broken. Again, only for a new app. My old app builds fine.

**Comment by jbavari** [comment]
Aha, I've found the bug. It's nestled down in cordova-lab. I'm going to have to adjust the fork Ive got for cordova-lib and make appropriate changes to patch this.

**Comment by mdridley** [comment]
Sweet, I think that would fix my issue. I was only playing with new apps for now.

**Comment by jbavari** [comment]
I think I've found the issue. 

I'm using cordova-lib under the hood to fire off the run, build, emulate, etc commands for cordova. Whats happening is some node packages that cordova-lib uses tries to use the `fork` command from node's `child_process` module.

This creates a problem in a few ways. The first is that `fork` in electron issues the request to the electron process (it is, after all, using io.js under the hood). When electron uses `fork`, it does not allow any stdio between the processes.

It's failing to change project settings with the `pbx` file that ios uses, since fork cannot run the [`xcode`](https://github.com/alunny/node-xcode/blob/master/lib/pbxProject.js#L23) commands that `cordova-lib` requires.

I've found using cordova-lib not to be very pleasant, especially from electron.

I've tried forking the `xcode` module and having it rely on `child_process.spawn` instead, however, now I'm running into EACCES issues, as the `xcode` package does not grant execute permissions on the `parseJob.js` file.

Running into one roadblock after another. Please bear with me!

**Comment by jbavari** [comment]
Should be fixed in next release.
