### ISSUE TITLE
Splash screen hangs after adding Splashscreen plugin

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-lab-issues#51]
After adding the Splashscreen plugin using ionc lab, my app hung and never finished loading while displaying the splash screen. I got the following error message in the console:

```
Uncaught ReferenceError: app is not defined
```

I noticed it added a nested "app.run" inside my app's **my_app_name.run**  function

```
my_app_name.run(function ($ionicPlatform, $cordovaStatusbar, $cordovaSplashscreen) {
    ...
    ...
    app.run(function($cordovaSplashScreen) {
      setTimeout(function() {
        $cordovaSplashScreen.hide()
      }, 5000)
    })
    ...
})
```

 Modifying the code as follows fixed the issue (in case anybody else encounters this situation)

```
  setTimeout(function() {
    $cordovaSplashScreen.hide()
  }, 5000)
```

**Comment by Ionitron** [comment]
Greetings @gigocabrera!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
