### ISSUE TITLE
console.log() not written to the log panel

### ISSUE THREAD

**Issue by danielmilner** [driftyco/ionic-lab-issues#56]
Anything output to `console.log()` does not show up in the log panel.

**Comment by Ionitron** [comment]
Greetings @danielmilner!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
