### ISSUE TITLE
Dragging app onto screen does not remove welcome overlay

### ISSUE THREAD

**Issue by cwoolum** [driftyco/ionic-lab-issues#72]
After dragging a project onto the app, I would expect the overlay to go away so I can work with the project. Overlay remains though and you have to x out of it.

![image](https://cloud.githubusercontent.com/assets/942415/9965235/b785ba34-5de9-11e5-8f0d-c97145e21fc9.png)

**Comment by Ionitron** [comment]
Greetings @cwoolum!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
