### ISSUE TITLE
lab would be much more useful if it included an ide

### ISSUE THREAD

**Issue by stgnet** [driftyco/ionic-lab-issues#74]
I loaded it just to see what it could do, and was honestly surprised I could not find a way to edit the application files.

**Comment by Ionitron** [comment]
Greetings @stgnet!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by stgnet** [comment]
I just tried the current version, and there is no ability to edit within the application.  This is more of a feature request than a bug.  Built in editing ability would add IDE-like workflow that would be of benefit to developers not already set on using their own editor, and make ionic easier for newbies to understand.
