### ISSUE TITLE
Windows - Platform components' style support

### ISSUE THREAD

**Issue by PBartrina** [driftyco/ionic-lab-issues#78]
It would be nice if, as announced on the web, the app showed the "look & feel" of every platform.
I am thinking about the Select component, although there are more than one.

**Comment by Ionitron** [comment]
Greetings @PBartrina!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
